# Generated by Django 4.2.4 on 2023-10-16 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=45)),
                ('postnom', models.CharField(max_length=45)),
                ('prenom', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Faculte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Filliere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=25)),
                ('faculte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_studentPresent.faculte')),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=15)),
                ('filliere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_studentPresent.filliere')),
            ],
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_studentPresent.courses')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_studentPresent.etudiant')),
            ],
        ),
        migrations.AddField(
            model_name='etudiant',
            name='promo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_studentPresent.promotion'),
        ),
        migrations.AddField(
            model_name='courses',
            name='enseignant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_studentPresent.enseignant'),
        ),
        migrations.AddField(
            model_name='courses',
            name='promo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_studentPresent.promotion'),
        ),
    ]
